import Foundation

/// Finds the archify system diagram that belongs to a tracked project.
///
/// The diagrams are generated by the `archify` skill into an Obsidian vault and
/// are read from there live rather than copied into the app bundle: regenerating
/// one should show up in ATLAS without a rebuild, and there should be exactly one
/// copy of each diagram in existence.
public enum ArchifyDiagrams {

    /// Where the generated diagrams live.
    ///
    /// The default is the live vault. `ATLAS_DIAGRAMS_DIR` overrides it, which is
    /// what the tests use and what covers the vault ever moving.
    public static var directory: URL {
        if let override = ProcessInfo.processInfo.environment["ATLAS_DIAGRAMS_DIR"], !override.isEmpty {
            return URL(fileURLWithPath: override)
        }
        return FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Documents/Obsidian/MYTHOS Context/diagrams", isDirectory: true)
    }

    /// The diagram for a project, or nil when that project has none.
    public static func diagram(for projectName: String, in directory: URL? = nil) -> URL? {
        let folder = directory ?? Self.directory
        guard let name = match(projectName, among: Set(stems(in: folder))) else { return nil }
        return folder.appendingPathComponent(name + ".html")
    }

    /// The matching rule on its own, against a set the caller already holds.
    ///
    /// The sidebar asks this for every visible row on every redraw, so it must
    /// not touch the disk; `diagram(for:)` and the sidebar share this function
    /// so the two can never disagree about what a project owns.
    public static func match(_ projectName: String, among names: Set<String>) -> String? {
        let wanted = slug(projectName)
        guard !wanted.isEmpty, !names.isEmpty else { return nil }

        if names.contains(wanted) { return wanted }

        // "Hermes" should find "hermes-sovereign", but a two-letter project must
        // not claim the first diagram that happens to start with those letters,
        // so prefix matching needs a name long enough to be meaningful.
        guard wanted.count >= 4 else { return nil }
        return names.filter { $0.hasPrefix(wanted + "-") }.sorted().first
    }

    /// Every diagram in the folder, as (slug, url), sorted by name.
    public static func all(in directory: URL? = nil) -> [(name: String, url: URL)] {
        let folder = directory ?? Self.directory
        return stems(in: folder).sorted().map {
            (name: $0, url: folder.appendingPathComponent($0 + ".html"))
        }
    }

    /// Every project slug that currently has a diagram.
    ///
    /// The sidebar marks rows from this, so it is a set lookup per row rather
    /// than a directory read per row.
    public static func availableSlugs(in directory: URL? = nil) -> Set<String> {
        Set(stems(in: directory ?? Self.directory))
    }

    public enum InstallError: LocalizedError {
        case notHTML(String)
        case unnameable

        public var errorDescription: String? {
            switch self {
            case .notHTML(let ext):
                return ext.isEmpty
                    ? "That file has no extension. Diagrams are .html files."
                    : "That is a .\(ext) file. Diagrams are .html files."
            case .unnameable:
                return "This project's name has no letters or digits to build a filename from."
            }
        }
    }

    /// Files a diagram into the folder under the name this project will look
    /// for, so dropping `some-export.html` onto MYTHOS Mobile stores it as
    /// `mythos-mobile.html` without anyone having to rename it.
    @discardableResult
    public static func install(_ source: URL,
                               for projectName: String,
                               in directory: URL? = nil) throws -> URL {
        let ext = source.pathExtension.lowercased()
        guard ext == "html" || ext == "htm" else { throw InstallError.notHTML(ext) }

        let name = slug(projectName)
        guard !name.isEmpty else { throw InstallError.unnameable }

        let folder = directory ?? Self.directory
        try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
        let destination = folder.appendingPathComponent(name + ".html")

        // Staged then swapped: a failed copy must not take out the diagram that
        // was already there.
        let staging = folder.appendingPathComponent(".\(name).incoming.html")
        try? FileManager.default.removeItem(at: staging)
        try FileManager.default.copyItem(at: source, to: staging)

        if FileManager.default.fileExists(atPath: destination.path) {
            _ = try FileManager.default.replaceItemAt(destination, withItemAt: staging)
        } else {
            try FileManager.default.moveItem(at: staging, to: destination)
        }
        return destination
    }

    // MARK: - internals

    /// The base names of the real diagrams in a folder.
    ///
    /// archify writes a `<name>.visual-check.html` contact sheet beside each
    /// diagram; that is a QA artefact, not something to offer as a diagram.
    private static func stems(in folder: URL) -> [String] {
        guard let entries = try? FileManager.default.contentsOfDirectory(
            at: folder, includingPropertiesForKeys: nil, options: [.skipsHiddenFiles]
        ) else { return [] }

        return entries
            .filter { $0.pathExtension == "html" }
            .map { $0.deletingPathExtension().lastPathComponent }
            .filter { !$0.hasSuffix(".visual-check") }
    }

    /// "MYTHOS Mobile" -> "mythos-mobile", so a display name can be compared
    /// with a filename. Public because the drop target names the file it is
    /// about to write, which is the part people otherwise get wrong.
    public static func slug(_ text: String) -> String {
        let lowered = text.lowercased()
        var out = ""
        var pendingSeparator = false
        for character in lowered {
            if character.isLetter || character.isNumber {
                if pendingSeparator && !out.isEmpty { out.append("-") }
                pendingSeparator = false
                out.append(character)
            } else {
                pendingSeparator = true
            }
        }
        return out
    }
}
